
services:
  postgres:
    image: postgres:15
    container_name: de_projet_10-postgres
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: kestra
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kestra"]
      interval: 5s
      timeout: 5s
      retries: 5

  kestra:
    image: kestra/kestra:v0.18.3
    container_name: de_projet_10-kestra
    command: server standalone 
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      KESTRA_FLOWS_FROM_PATH: "true" 
      KESTRA_FLOWS_PATH: "/app/flows"
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: kestra
        kestra:
          repository:
            type: postgres
          queue:
            type: postgres
          storage:
            type: local
            local:
              basePath: /tmp/kestra-storage
    volumes:
      - ./kestra/flows:/app/flows
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./duckdb:/app/duckdb

volumes:
  postgres_data: